export const CUSTOMER_GET_REQUEST = "CUSTOMER_GET_REQUEST";
export const CUSTOMER_GET_SUCCESS = "CUSTOMER_GET_SUCCESS";
export const CUSTOMER_GET_FAIL = "CUSTOMER_GET_FAIL";

export const CUSTOMER_APPEND_SUCCESS = "CUSTOMER_APPEND_SUCCESS";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_REMOVE_SUCCESS = "CUSTOMER_REMOVE_SUCCESS";

export const CUSTOMER_ADDING_REQUEST = "CUSTOMER_ADDED_REQUEST";
export const CUSTOMER_ADDING_SUCCESS = "CUSTOMER_ADDED_SUCCESS";
export const CUSTOMER_ADDING_FAIL = "CUSTOMER_ADDED_FAIL";

export const CUSTOMER_EDIT_REQUEST = "CUSTOMER_EDIT_REQUEST"
export const CUSTOMER_EDIT_SUCCESS = "CUSTOMER_EDIT_SUCCESS"
export const CUSTOMER_EDIT_FAIL = "CUSTOMER_EDIT_FAIL"

export const CUSTOMER_DELETE_REQUEST = "CUSTOMER_DELETE_REQUEST"
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS"
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL"

export const SINGLE_CUSTOMER_TRANSACTION_GET_REQUEST = "SINGLE_CUSTOMER_TRANSACTION_GET_REQUEST"
export const SINGLE_CUSTOMER_TRANSACTION_GET_SUCCESS = "SINGLE_CUSTOMER_TRANSACTION_GET_SUCCESS"
export const SINGLE_CUSTOMER_TRANSACTION_GET_FAIL = "SINGLE_CUSTOMER_TRANSACTION_GET_FAIL"

export const SINGLE_CUSTOMER_TRANSACTION_ADDING_REQUEST = "SINGLE_CUSTOMER_TRANSACTION_ADDING_REQUEST"
export const SINGLE_CUSTOMER_TRANSACTION_ADDING_SUCCESS = "SINGLE_CUSTOMER_TRANSACTION_ADDING_SUCCESS"
export const SINGLE_CUSTOMER_TRANSACTION_ADDING_FAIL = "SINGLE_CUSTOMER_TRANSACTION_ADDING_FAIL"

export const SINGLE_CUSTOMER_TRANSACTION_APPEND_SUCCESS = "SINGLE_CUSTOMER_TRANSACTION_APPEND_SUCCESS"

export const SINGLE_CUSTOMER_TRANSACTION_UPDATE_SUCCESS = "SINGLE_CUSTOMER_TRANSACTION_UPDATE_SUCCESS"

export const SINGLE_CUSTOMER_TRANSACTION_EDIT_REQUEST = "SINGLE_CUSTOMER_TRANSACTION_EDIT_REQUEST"
export const SINGLE_CUSTOMER_TRANSACTION_EDIT_SUCCESS = "SINGLE_CUSTOMER_TRANSACTION_EDIT_SUCCESS"
export const SINGLE_CUSTOMER_TRANSACTION_EDIT_FAIL = "SINGLE_CUSTOMER_TRANSACTION_EDIT_FAIL"

export const CUSTOMERS_BALANCE_GET_REQUEST="CUSTOMERS_BALANCE_GET_REQUEST"
export const CUSTOMERS_BALANCE_GET_SUCCESS="CUSTOMERS_BALANCE_GET_SUCCESS"
export const CUSTOMERS_BALANCE_GET_FAIL="CUSTOMERS_BALANCE_GET_FAIL"

export const SINGLE_CUSTOMER_DETAILS_FETCH_REQUEST="SINGLE_CUSTOMER_DETAILS_FETCH_REQUEST"
export const SINGLE_CUSTOMER_DETAILS_FETCH_SUCCESS="SINGLE_CUSTOMER_DETAILS_FETCH_SUCCESS"
export const SINGLE_CUSTOMER_DETAILS_FETCH_ERROR="SINGLE_CUSTOMER_DETAILS_FETCH_ERROR"
export const 	SINGLE_CUSTOMER_DETAILS_UPDATE_SUCCESS="SINGLE_CUSTOMER_DETAILS_UPDATE_SUCCESS"
export const SINGLE_CUSTOMER_DETAILS_DELETE_SUCCESS="SINGLE_CUSTOMER_DETAILS_DELETE_SUCCESS"