export const SUPPLIER_GET_REQUEST = "SUPPLIER_GET_REQUEST";
export const SUPPLIER_GET_SUCCESS = "SUPPLIER_GET_SUCCESS";
export const SUPPLIER_GET_FAIL = "SUPPLIER_GET_FAIL";

export const SUPPLIER_APPEND_SUCCESS = "SUPPLIER_APPEND_SUCCESS";
export const SUPPLIER_UPDATE_SUCCESS = "SUPPLIER_UPDATE_SUCCESS";
export const SUPPLIER_REMOVE_SUCCESS = "SUPPLIER_REMOVE_SUCCESS";

export const SUPPLIER_ADDING_REQUEST = "SUPPLIER_ADDED_REQUEST";
export const SUPPLIER_ADDING_SUCCESS = "SUPPLIER_ADDED_SUCCESS";
export const SUPPLIER_ADDING_FAIL = "SUPPLIER_ADDED_FAIL";

export const SUPPLIER_EDIT_REQUEST = "SUPPLIER_EDIT_REQUEST"
export const SUPPLIER_EDIT_SUCCESS = "SUPPLIER_EDIT_SUCCESS"
export const SUPPLIER_EDIT_FAIL = "SUPPLIER_EDIT_FAIL"

export const SUPPLIER_DELETE_REQUEST = "SUPPLIER_DELETE_REQUEST"
export const SUPPLIER_DELETE_SUCCESS = "SUPPLIER_DELETE_SUCCESS"
export const SUPPLIER_DELETE_FAIL = "SUPPLIER_DELETE_FAIL"

export const SINGLE_SUPPLIER_TRANSACTION_GET_REQUEST = "SINGLE_SUPPLIER_TRANSACTION_GET_REQUEST"
export const SINGLE_SUPPLIER_TRANSACTION_GET_SUCCESS = "SINGLE_SUPPLIER_TRANSACTION_GET_SUCCESS"
export const SINGLE_SUPPLIER_TRANSACTION_GET_FAIL = "SINGLE_SUPPLIER_TRANSACTION_GET_FAIL"

export const SINGLE_SUPPLIER_TRANSACTION_ADDING_REQUEST = "SINGLE_SUPPLIER_TRANSACTION_ADDING_REQUEST"
export const SINGLE_SUPPLIER_TRANSACTION_ADDING_SUCCESS = "SINGLE_SUPPLIER_TRANSACTION_ADDING_SUCCESS"
export const SINGLE_SUPPLIER_TRANSACTION_ADDING_FAIL = "SINGLE_SUPPLIER_TRANSACTION_ADDING_FAIL"

export const SINGLE_SUPPLIER_TRANSACTION_APPEND_SUCCESS = "SINGLE_SUPPLIER_TRANSACTION_APPEND_SUCCESS"

export const SINGLE_SUPPLIER_TRANSACTION_UPDATE_SUCCESS = "SINGLE_SUPPLIER_TRANSACTION_UPDATE_SUCCESS"

export const SINGLE_SUPPLIER_TRANSACTION_EDIT_REQUEST = "SINGLE_SUPPLIER_TRANSACTION_EDIT_REQUEST"
export const SINGLE_SUPPLIER_TRANSACTION_EDIT_SUCCESS = "SINGLE_SUPPLIER_TRANSACTION_EDIT_SUCCESS"
export const SINGLE_SUPPLIER_TRANSACTION_EDIT_FAIL = "SINGLE_SUPPLIER_TRANSACTION_EDIT_FAIL"

export const SUPPLIERS_BALANCE_GET_REQUEST="SUPPLIERS_BALANCE_GET_REQUEST"
export const SUPPLIERS_BALANCE_GET_SUCCESS="SUPPLIERS_BALANCE_GET_SUCCESS"
export const SUPPLIERS_BALANCE_GET_FAIL="SUPPLIERS_BALANCE_GET_FAIL"

export const SINGLE_SUPPLIER_DETAILS_FETCH_REQUEST="SINGLE_SUPPLIER_DETAILS_FETCH_REQUEST"
export const SINGLE_SUPPLIER_DETAILS_FETCH_SUCCESS="SINGLE_SUPPLIER_DETAILS_FETCH_SUCCESS"
export const SINGLE_SUPPLIER_DETAILS_FETCH_ERROR="SINGLE_SUPPLIER_DETAILS_FETCH_ERROR"
export const 	SINGLE_SUPPLIER_DETAILS_UPDATE_SUCCESS="SINGLE_SUPPLIER_DETAILS_UPDATE_SUCCESS"
export const SINGLE_SUPPLIER_DETAILS_DELETE_SUCCESS="SINGLE_SUPPLIER_DETAILS_DELETE_SUCCESS"